spring.application.name=demo

# AWS S3 Configuration
aws.s3.access-key=${AWS_ACCESS_KEY:placeholder}
aws.s3.secret-key=${AWS_SECRET_KEY:placeholder}
aws.s3.region=us-east-2
aws.s3.bucket-name=trustedproductimages

# AWS DynamoDB Configuration
aws.dynamodb.access-key=${AWS_ACCESS_KEY:placeholder}
aws.dynamodb.secret-key=${AWS_SECRET_KEY:placeholder}
aws.dynamodb.region=us-east-2
aws.dynamodb.endpoint=https://dynamodb.us-east-2.amazonaws.com
aws.dynamodb.table.user-details=userdetails
aws.dynamodb.table-name=products
aws.dynamodb.table.wishlist=userwishlist

# Feature Toggle Configuration
feature.search_table.enabled=true
feature.search_table.university_filter_percentage=100
feature.search_table.city_filter_percentage=100
feature.search_table.category_filter_percentage=0
feature.search_table.featured_percentage=0
feature.search_table.new_arrivals_percentage=100