spring.application.name=demo

# AWS S3 Configuration
aws.s3.access-key=YOUR_ACCESS_KEY_HERE
aws.s3.secret-key=YOUR_SECRET_KEY_HERE
aws.s3.region=us-east-2
aws.s3.bucket-name=trustedproductimages

# AWS DynamoDB Configuration
aws.dynamodb.access-key=YOUR_ACCESS_KEY_HERE
aws.dynamodb.secret-key=YOUR_SECRET_KEY_HERE
aws.dynamodb.region=us-east-2
aws.dynamodb.endpoint=https://dynamodb.us-east-2.amazonaws.com
aws.dynamodb.table.user-details=userdetails